name: Deploy Client Next

on:
  push:
    paths:
      - 'apps/frontend/**'
      - 'packages/types/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -tt -i keyfile ubuntu@ec2-18-207-149-56 "sudo bash /home/ubuntu/sol-zap/apps/frontend/deploy.sh"